inbound:
  channel:
    remote:
      # rest call delay to coinbase api for different crypto currencies
      btc: 1000
      eth: 100
      ltc: 2000
  stubs:
    throttle: 100 # throttle im ms
server:
  port: 9090

logging:
  level:
    org.springframework.web: DEBUG

management.endpoints.web.expose: "*"
