inbound:
  stubs:
    throttle:
      # throttle im ms
      btc: 1000
      eth: 100
      ltc: 2000
server:
  port: 9090

logging:
  level:
    org.springframework.web: DEBUG

management.endpoints.web.expose: "*"
