inbound:
  stubs:
    throttle: 500 # throttle im ms
server:
  port: 9090

logging:
  level:
    org.springframework: DEBUG

management.endpoints.web.expose: "*"


coinbase.api.url: https://api.coinbase.com/v2/
